In [3]:
import numpy as np

## 1. Data Types & Attributes

In [4]:
# NumPy's main data type is `nparray`
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]
              ])


In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
# number of elements in the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a data frame from nparray
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [24]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [32]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
zeros.dtype

dtype('float64')

In [34]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0, 10, size =(3, 5))
random_array

array([2, 4])

In [37]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [41]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.27912344, 0.53405406, 0.36471053],
       [0.07876616, 0.43649119, 0.78437431],
       [0.38389398, 0.20314821, 0.78677337],
       [0.19366903, 0.63231425, 0.30175101],
       [0.90813096, 0.34746631, 0.47301351]])

In [42]:
random_array2.shape

(5, 3)

In [44]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.46260009, 0.76807488, 0.96851561],
       [0.62859347, 0.49325553, 0.4618756 ],
       [0.15838446, 0.46029151, 0.96892253],
       [0.56434301, 0.11012037, 0.1292335 ],
       [0.10074692, 0.28797837, 0.44906242]])

In [57]:
# Pseudo-random numbers
np.random.seed(seed=42)

random_array4 = np.random.randint(0, 10, size =(5, 3))
random_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [51]:
random_array4.shape

(5, 3)

## 3. Viewing Arrays

In [58]:
np.unique(random_array4)

array([2, 3, 4, 5, 6, 7, 9])

In [59]:
a1

array([1, 2, 3])

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [61]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [62]:
a1[0]

1

In [68]:
a2[0,2]

3.3

In [65]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
# slicing
a3[:, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [77]:
# dimensions are set backwards from innermost to outermost
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 8, 4, 5, 3],
         [9, 6, 8, 6, 0],
         [0, 8, 8, 3, 8],
         [2, 6, 5, 7, 8]],

        [[4, 0, 2, 9, 7],
         [5, 7, 8, 3, 0],
         [0, 9, 3, 6, 1],
         [2, 0, 4, 0, 7]],

        [[0, 0, 1, 1, 5],
         [6, 4, 0, 0, 2],
         [1, 4, 9, 5, 6],
         [3, 6, 7, 0, 5]]],


       [[[7, 4, 3, 1, 5],
         [5, 0, 8, 5, 2],
         [3, 3, 2, 9, 2],
         [2, 3, 6, 3, 8]],

        [[0, 7, 6, 1, 7],
         [0, 8, 8, 1, 6],
         [9, 2, 6, 9, 8],
         [3, 0, 1, 0, 4]],

        [[4, 6, 8, 8, 2],
         [2, 2, 3, 7, 5],
         [7, 0, 7, 3, 0],
         [7, 3, 5, 7, 3]]]])

In [78]:
# get only 4 numbers of the innermost array
a4[:, :, :, :4]

array([[[[9, 8, 4, 5],
         [9, 6, 8, 6],
         [0, 8, 8, 3],
         [2, 6, 5, 7]],

        [[4, 0, 2, 9],
         [5, 7, 8, 3],
         [0, 9, 3, 6],
         [2, 0, 4, 0]],

        [[0, 0, 1, 1],
         [6, 4, 0, 0],
         [1, 4, 9, 5],
         [3, 6, 7, 0]]],


       [[[7, 4, 3, 1],
         [5, 0, 8, 5],
         [3, 3, 2, 9],
         [2, 3, 6, 3]],

        [[0, 7, 6, 1],
         [0, 8, 8, 1],
         [9, 2, 6, 9],
         [3, 0, 1, 0]],

        [[4, 6, 8, 8],
         [2, 2, 3, 7],
         [7, 0, 7, 3],
         [7, 3, 5, 7]]]])