In [2]:
import numpy as np

## 1. Data Types & Attributes

In [3]:
# NumPy's main data type is `nparray`
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]
              ])


In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
# number of elements in the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a data frame from nparray
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size =(3, 5))
random_array

array([[5, 9, 4, 5, 9],
       [1, 3, 2, 9, 7],
       [6, 9, 4, 8, 8]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.61334529, 0.91564162, 0.99096194],
       [0.96738418, 0.8918498 , 0.93426161],
       [0.56404356, 0.38733662, 0.29958352],
       [0.10182555, 0.72292022, 0.0717381 ],
       [0.93630219, 0.90052363, 0.06153166]])

In [28]:
random_array2.shape

(5, 3)

In [29]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.94240193, 0.54554275, 0.73850532],
       [0.45504168, 0.78853532, 0.83905706],
       [0.13714582, 0.04539526, 0.86601645],
       [0.06664283, 0.53963191, 0.64525808],
       [0.01504316, 0.96088959, 0.66436683]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=42)

random_array4 = np.random.randint(0, 10, size =(5, 3))
random_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [31]:
random_array4.shape

(5, 3)

## 3. Viewing Arrays

In [32]:
np.unique(random_array4)

array([2, 3, 4, 5, 6, 7, 9])

In [33]:
a1

array([1, 2, 3])

In [34]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1[0]

1

In [37]:
a2[0,2]

3.3

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# slicing
a3[:, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
# dimensions are set backwards from innermost to outermost
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]])

In [41]:
# get only 4 numbers of the innermost array
a4[:, :, :, :4]

array([[[[4, 1, 7, 5],
         [4, 0, 9, 5],
         [0, 9, 2, 6],
         [8, 2, 4, 2]],

        [[4, 8, 6, 1],
         [8, 1, 9, 8],
         [4, 1, 3, 6],
         [2, 0, 3, 1]],

        [[3, 1, 5, 5],
         [3, 5, 1, 9],
         [9, 3, 7, 6],
         [7, 4, 1, 4]]],


       [[[9, 8, 8, 0],
         [6, 8, 7, 0],
         [7, 2, 0, 7],
         [2, 0, 4, 9]],

        [[9, 8, 6, 8],
         [1, 0, 6, 6],
         [4, 2, 7, 5],
         [0, 2, 4, 2]],

        [[4, 9, 6, 6],
         [9, 9, 2, 6],
         [3, 3, 4, 6],
         [3, 6, 2, 5]]]])

## 4. Manipulating & comparing Arrays

### Arithmetic

In [42]:
a1

array([1, 2, 3])

In [43]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [44]:
a1 + ones

array([2., 3., 4.])

In [45]:
a1 - ones

array([0., 1., 2.])

In [46]:
a1 * ones

array([1., 2., 3.])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a2 * a1

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a2 * a3 # broadcasting can't be applied

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

NumPy broadcasting rules: [Link](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In order to be able to broadcast a [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) might be necessary

In [69]:
a4 = np.reshape(a2, a3.shape)

ValueError: cannot reshape array of size 6 into shape (2,3,3)

In [54]:
a3.shape

(2, 3, 3)

In [55]:
a2.shape

(2, 3)

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a1 / ones

array([1., 2., 3.])

In [62]:
# floor division removes decimals (round-off)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [61]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [63]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [64]:
a1 % 2

array([1, 0, 1])

In [65]:
np.mod(a1, 2)

array([1, 0, 1])

In [66]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [67]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [68]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [70]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [71]:
sum(listy_list)

6

In [74]:
a1, type(a1)

(array([1, 2, 3]), numpy.ndarray)

In [72]:
np.sum(a1)

6

Use Python's methods on Python data types (`sum()`) and
use NumPy's methods on NumPy array (`np.sum()`)

In [77]:
# Create a massive array
massive_array = np.random.random(100000)
massive_array.size

100000

In [78]:
massive_array[:10]

array([0.62435405, 0.29563369, 0.10549426, 0.45653457, 0.21844044,
       0.41650995, 0.88328026, 0.32434502, 0.12208795, 0.35629784])

In [79]:
%timeit sum(massive_array) # Python sum
%timeit np.sum(massive_array) # NumPy sum

4.19 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.5 µs ± 96.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [80]:
4.19*1000 / 20.5

204.390243902439

In [81]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [82]:
np.mean(a2)

3.6333333333333333

In [84]:
np.min(a2), np.max(a2)

(1.0, 6.5)

In [87]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [88]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = higher range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [89]:
np.sqrt(np.var(a2))

1.8226964152656422